# SPDX-License-Identifier: MIT

# Custom tap hosting previous versions
tap "fnstruct/tap"

brew "bat"
brew "editorconfig"
brew "git"
brew "gnupg"
brew "lf"
brew "libfaketime"
brew "libusbmuxd"
brew "lsd"
brew "micro"
brew "pinentry-mac"
brew "stow"
brew "zsh-syntax-highlighting"

cask "firefox@esr"
cask "fnstruct/tap/eloston-chromium"
cask "fnstruct/tap/iterm2"
cask "font-sf-mono"
cask "utm"
